### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by matkoniecz**

### CODE REVIEW

**Comment by missinglink** [comment]
FYI there seems to be a git conflict artefact at the top of the README?

Screenshot_20200521-085322

**Comment by matkoniecz** [comment]
I thought that it was some kind of joke and intentional, so I limited myself to typos in this "is this project alive" probing PR.

**Comment by missinglink** [comment]
@matkoniecz I noticed you opened a couple issues recently across a range of coarse-geocoding related open-source repos and thought I'd mention https://github.com/pelias/placeholder as another option for you.

**Comment by matkoniecz** [comment]
@missinglink I was [reviewing and updating](https://wiki.openstreetmap.org/w/index.php?title=Search_engines&type=revision&diff=1993356&oldid=1988159) https://wiki.openstreetmap.org/wiki/Search_engines#Search_engine_software - in case of Pelias there was nothing obviously broken in their repo.

**Comment by kiselev-dv** [comment]
Oh Sorry guys, didn't follow on PRs to my stuff.

**Pull request merged**
